name: ReleaseBuild

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  SOLUTION_FILE_PATH: project/GE3.sln
  CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Build
        shell: cmd
        run: |
          msbuild "${{ env.SOLUTION_FILE_PATH }}" ^
            /p:Platform=${{ env.PLATFORM }},Configuration=${{ env.CONFIGURATION }} ^
            /m
